### ISSUE TITLE
inbo_palette too strict?

### ISSUE THREAD

**Issue by pietervsd** [inbo/INBOtheme#15]
when the factor levels exceed the palette size (9), is a warning not sufficient, instead of triggering an error?

**Comment by ThierryO** [comment]
The old version recycled the colours. And having more than 9 discrete colours is seldom a good idea. Hence an error seems more appropriate to me.

**Comment by SanderDevisscher** [comment]
@ThierryO we use more categories than 9 for the [grofwildjacht - app](https://grofwildjacht.inbo.be/). This error makes the "FIGUUR: Aantal schademeldingen per jaar en variabele" with variable "gewas" (when selecting wild boar as species) not displayable since damage to more than 9 types of crop were reported. Can you please set it back to a warning instead of an error?

**Comment by pietervsd** [comment]
A lot of my scripts break because of changing the warning to error and the default behaviour in ggplot is also a warning. Not in all cases the colours are used as factor levels, but often they are just aesthetical, like to have a line per site. The colours themselves have no meaning then, but are still useful and just using the groups argument gives all the same colour which is not desired.

**Comment by ThierryO** [comment]
`ggplot2::scale_colour_discrete()` uses a systematic sample along a range of hues. Therefore it is able to generate as much colours as you ask it to provide. More colours  = less difference among the colours.

`inbo_palette(n)` works different. It has a predefined list of 9 colours of which it returns the first `n`. Having more than seven colours in a plot is not a good idea as it because hard to identify the category that matches the colour. If you need more than nine colours to identify categories, then IMHO you should rethink your figure. When colours don't have a meaning, then why use colours?

```
library(ggplot2)
ds <- expand.grid(x = 1:5, y = 1:5)
ds$color <- factor(seq_along(ds$x))
ggplot(ds, aes(x = x, y = y, fill = color)) + geom_tile()
```
![image](https://user-images.githubusercontent.com/446636/103775973-14f1ad80-502f-11eb-8843-be58634f681a.png)

```
ds <- expand.grid(x = 1:10, y = 1:10)
ds$color <- factor(seq_along(ds$x))
ggplot(ds, aes(x = x, y = y, fill = color)) + geom_tile()
```
![image](https://user-images.githubusercontent.com/446636/103776025-2b980480-502f-11eb-8a55-72ea4f880157.png)
