### ISSUE TITLE
Error: object ‘inbo.lichtblauw’ is not exported by 'namespace:INBOtheme'

### ISSUE THREAD

**Issue by SanderDevisscher** [inbo/INBOtheme#16]
Deze error krijg ik wanneer ik poog [reportingGrofwild](https://github.com/inbo/reporting-rshiny-grofwildjacht) te builden in docker. 
De dockerfile van deze app instaleert steeds de nieuwste versie van INBOtheme, zie deze link:

https://github.com/inbo/reporting-rshiny-grofwildjacht/blob/46fd9f15452531ec17dc73187e89d6831740c2f9/Dockerfile#L29

Ik vermoed dat in de laatste 3 maanden een aanpassing is gebeurd waardoor "inbo.lichtblauw" niet meer behoort tot de opties van INBOtheme. Klopt dit ? Zoja, hoe los ik dit op? 

Het is nogal dringend !!

**Comment by ElsLommelen** [comment]
Blijkbaar zijn de punten in de kleurnamen vervangen door underscores, dus probeer eens met `inbo_lichtblauw`

**Comment by SanderDevisscher** [comment]
@ElsLommelen dank je.
De punten in de kleuren zijn idd vervangen door een underscore.

**Comment by ThierryO** [comment]
This breaking change is mentioned in the [startup message](https://github.com/inbo/INBOtheme/blob/93305f88979a4f88539e115793b35bf471d9dacd/R/on_load.R#L20) and in [NEWS.md](https://github.com/inbo/INBOtheme/blob/master/NEWS.md#inbotheme-057)

**Comment by ElsLommelen** [comment]
@ThierryO @florisvdh 
Would it be an idea to announce such breaking changes in INBO packages (or often used packages) the `OSD nieuwsbrief`?

Yesterday I got a similar question on this topic, and honestly, when I am forced to update all my packages due to an unexpected R update in a busy period, I also don't read all news items of all packages I reinstall.  And though the startup message is very clear in the R console, I see now, I didn't notice it yesterday when solving this problem in a Rmd file sent by another user.  When starting a new script, I'm sure one would notice the message immediately, but when rerunning an old script which has always worked fine, the message might get lost, I noticed...  So a newsletter item to announce breaking changes once more, could be helpful in my opinion.

**Comment by florisvdh** [comment]
That sounds like a good idea - of course it depends for which packages you'd consider that (there's a risk of growing too large, considering the many package developments at INBO). But for updates of general-purpose packages such as INBOtheme, I believe that fits well in the 'new developments' part. For more specific/specialized stuff, such information could be spread through our useR mailing list or to a specific user group.

**Comment by SanderDevisscher** [comment]
> This breaking change is mentioned in the [startup message](https://github.com/inbo/INBOtheme/blob/93305f88979a4f88539e115793b35bf471d9dacd/R/on_load.R#L20) and in [NEWS.md](https://github.com/inbo/INBOtheme/blob/master/NEWS.md#inbotheme-057)

In the R-console yes! But I didn't notice it while building the app **in Docker**!!

I'm also a proponent of announcing breaking changes (like this issue and #15) in some sort of newsletter.
