### ISSUE TITLE
use of INBO colour palette with ggmap

### ISSUE THREAD

**Issue by ElsLommelen** [inbo/INBOtheme#22]
I noticed that using INBOtheme, the INBO colour palette is not automatically added when using ggmap instead of ggplot2.  So when using both ggmap and ggplot2 in the same report, ggmap pictures have the standard R colour palette while ggplot2 pictures have the INBO palette when not configuring the colours manually.

`ggplot() + geom_sf()` gives subsequently inbo_groen, inbo_steun_blauw, inbo_oranje,... (INBO palette) in the legend,
while `ggmap() + geom_sf()` gives subsequently pink, green, blue,... (standard R colour palette) in the legend.
So when using the same categories in the legend, one has to adapt one of the colour palettes to align them with each other.

I loaded ggplot2 and ggmap before INBOtheme, so I suppose this functionality is not present at INBOtheme at the moment?

**Comment by ThierryO** [comment]
When two packages use the same function name, the function of the latest loaded package is used. It masks the previously loaded function with that name. `INBOtheme` masks `scale_colour_discrete()` from `ggplot2`. That's why you need to load `INBOtheme` after `ggplot2`.

I guess that `ggmap()` doesn't call `scale_colour_discrete()`. Or imports `scale_colour_discrete()` from `ggplot2`. Is such case it will always use `ggplot2::scale_colour_discrete()`. What happesn if you run `ggmap() + geom_sf() + scale_colour_discrete()` or `ggmap() + geom_sf() + INBOtheme::scale_colour_discrete()`?

**Comment by ElsLommelen** [comment]
Adding `+ scale_colour_discrete()` gives the INBO palette and thus solves the issue, specifying package `INBOtheme` seems not necessary.  Thanks!
